services:
  db:
    image: mysql:8.0
    container_name: alfalog_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${APP_DB_PASS}
      MYSQL_DATABASE: ${APP_DB_NAME}
      MYSQL_USER: ${APP_DB_USER}
      MYSQL_PASSWORD: ${APP_DB_PASS}
    volumes:
      - mysql_alfalog_data:/var/lib/mysql
    ports:
      - "${APP_DB_PORT:-3306}:3306"
    healthcheck:
        test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
        interval: 10s
        timeout: 5s
        retries: 5
        start_period: 30s
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: alfalog_backend
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "5000:5000"
    volumes:
      - .:/app  # For development with live reload
      - ./.env:/app/.env  # Mount the .env file into the container

volumes:
  mysql_alfalog_data:
    driver: local
