services:
  db:
    image: mysql:8.0
    container_name: mysql_alfalog_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${APP_DB_PASS}
      MYSQL_DATABASE: ${APP_DB_NAME}
      MYSQL_USER: ${APP_DB_USER}
      MYSQL_PASSWORD: ${APP_DB_PASS}
    volumes:
      - mysql_alfalog_data:/var/lib/mysql
      - ./database/init.sql:/docker-entrypoint-initdb.d/seed.sql
    ports:
      - "3306:3306"
    healthcheck:
        test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
        interval: 10s
        timeout: 5s
        retries: 5
        start_period: 30s

  app_init:
    build: .
    container_name: python_db_initializer
    restart: 'no'
    env_file:
      - .env
    volumes:
      - ./data/dados_comex_EXP_2014_2024.csv:/data/dados_comex_EXP_2014_2024.csv:ro
    environment:
      APP_DB_HOST: db
      FLASK_APP: ${FLASK_APP:-src}
    depends_on:
      db:
        condition: service_healthy

volumes:
  mysql_alfalog_data:
    driver: local